### ISSUE TITLE
Opening icecast link crashes otter.

### ISSUE THREAD

**Issue by vext01** [OtterBrowser/otter-browser#1063]
When I open http://ice1.somafm.com/groovesalad-128-mp3 on Otter-0.9.09 on OpenBSD, the browser crashes.

Cheers

**Comment by Emdek** [comment]
@vext01, which Qt version are you using?
Could you please test it using this our test application?
https://github.com/OtterBrowser/test-qtwebkit

**Comment by vext01** [comment]
It crashes using the test app as well.

**Comment by vext01** [comment]
```
$ pkg_info | grep qt5
qt5-5.4.1p9         C++ general-purpose toolkit
```

**Comment by vext01** [comment]
Gdb trace (QT5 doesn't have symbols):

```
(gdb) run
Starting program: /home/edd/source/test-qtwebkit/test-qtwebkit 
warning: Lowest section in /usr/local/lib/libicudata.so.9.0 is .hash at 0000000000000200

Program received signal SIGABRT, Aborted.
0x000001ed5263b87a in thrkill () at <stdin>:2
2       <stdin>: No such file or directory.
        in <stdin>
Current language:  auto; currently asm
(gdb) bt
#0  0x000001ed5263b87a in thrkill () at <stdin>:2
#1  0x000001ed52636f39 in *_libc_abort ()
    at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x000001ee038ad028 in _rthread_mutex_lock (mutexp=0x1edeb3598b0, 
    trywait=0, abstime=0x0) at /usr/src/lib/librthread/rthread_sync.c:127
#3  0x000001eda6954c91 in g_mutex_lock ()
   from /usr/local/lib/libglib-2.0.so.4200.2
#4  0x000001ed6c304dbd in gst_object_get_parent (object=0x1edeb3609e0)
    at gstobject.c:740
#5  0x000001ed6c305d00 in gst_object_dispatch_properties_changed (
    object=0x1edeb3609e0, n_pspecs=1, pspecs=0x7f7ffffec738) at gstobject.c:459
#6  0x000001ee1944e352 in g_object_notify ()
   from /usr/local/lib/libgobject-2.0.so.4200.2
#7  0x000001eded504470 in StreamingClient::handleResponseReceived ()
   from /usr/local/lib/qt5/libQt5WebKit.so.1.0
#8  0x000001eded1ab29b in WebCore::CachedRawResource::responseReceived ()
   from /usr/local/lib/qt5/libQt5WebKit.so.1.0
#9  0x00007f7ffffec8b0 in ?? ()
#10 0x000001ed86ced000 in ?? ()
#11 0x000001ed86ced128 in ?? ()
#12 0x00007f7ffffec810 in ?? ()
#13 0x000001ed86ced000 in ?? ()
#14 0x00007f7ffffec940 in ?? ()
---Type <return> to continue, or q <return> to quit---
#15 0x000001ee1a183a20 in ?? ()
#16 0xdc3c9e1553444fbd in ?? ()
#17 0x000001ed82f84820 in ?? ()
#18 0x00007f7ffffec980 in ?? ()
#19 0x00007f7ffffec9e0 in ?? ()
#20 0x000001edffe72c00 in ?? ()
#21 0x000001ed8ca59301 in ?? ()
#22 0x00007f7ffffec970 in ?? ()
#23 0x00007f7ffffec940 in ?? ()
#24 0x000001eded202c70 in WebCore::SubresourceLoader::didReceiveResponse ()
   from /usr/local/lib/qt5/libQt5WebKit.so.1.0
#25 0x000001eded425d22 in WebCore::QNetworkReplyHandler::sendResponseIfNeeded
    () from /usr/local/lib/qt5/libQt5WebKit.so.1.0
#26 0x00007f7ffffec960 in ?? ()
#27 0x00007f7ffffec930 in ?? ()
#28 0x00007f7ffffec970 in ?? ()
#29 0x00007f7ffffec980 in ?? ()
#30 0x000001edffe72c00 in ?? ()
#31 0x000001ed8ca59380 in ?? ()
#32 0x000001ed82f825e0 in ?? ()
#33 0x1b172ae16b0784e9 in ?? ()
#34 0x0000000000000000 in ?? ()
```

**Comment by Emdek** [comment]
Hopefully it is no longer reproducible when using revived QtWebKit.
