### ISSUE TITLE
Right-click context menu cannot be opened after navigating.

### ISSUE THREAD

**Issue by elebow** [OtterBrowser/otter-browser#1092]
The context menu does not appear for any tabs after navigating to a page. OpenLinkInNewTabAction also does not function.

However, these actions do work correctly for any tabs that are loaded when the session starts. They only break after navigating.

Normal navigating (left-clicking a link) continues to work the entire time.

Using latest master with Qt 5.6.0 and QtWebEngine backend.

**Comment by elebow** [comment]
On the latest master (c678bf2d34d6399eef2fa0e214a3f9533405ce90), a segfault occurs when opening a link in a new tab after navigating. A backtrace is attached. I believe this has the same root cause as the behavior described in this issue.

Steps to reproduce:
1. Open a fresh session with a fresh profile
2. Navigate to a website with links (for example, wikipedia.org)
3. Open any link in a new tab
4. Program segfaults

The crash does not happen on 7a798f668db0b64b4f99d4a68c49b83a137e2736.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1e16822 in QtWebEngineCore::UserScriptControllerHost::clearAllScripts(QtWebEngineCore::WebContentsAdapter*) ()
   from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
(gdb) bt
#0  0x00007ffff1e16822 in QtWebEngineCore::UserScriptControllerHost::clearAllScripts(QtWebEngineCore::WebContentsAdapter*) ()
   from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#1  0x000000000076b1b1 in Otter::QtWebEnginePage::pageLoadStarted() ()
#2  0x00000000007a1c13 in Otter::QtWebEnginePage::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#3  0x00007ffff7b5cc0f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#4  0x00007ffff7f95a6c in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineWidgets.so.5
#5  0x00007ffff1e1fd8e in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#6  0x00007ffff2a0e3af in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#7  0x00007ffff2ae7417 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#8  0x00007ffff2910e4b in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#9  0x00007ffff298782e in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#10 0x00007ffff324d660 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#11 0x00007ffff35e0ad1 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#12 0x00007ffff358e9c4 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#13 0x00007ffff358eca1 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#14 0x00007ffff358f70b in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#15 0x00007ffff1debf13 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5WebEngineCore.so.5
#16 0x00007ffff7b5e1db in QObject::event(QEvent*) () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#17 0x00007ffff678173c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/Qt-5.6.0/lib/libQt5Widgets.so.5
#18 0x00007ffff6785c08 in QApplication::notify(QObject*, QEvent*) () from /usr/local/Qt-5.6.0/lib/libQt5Widgets.so.5
#19 0x00007ffff7b33b00 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#20 0x00007ffff7b36323 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#21 0x00007ffff7b83403 in ?? () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#22 0x00007fffeda6cc5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fffeda6cf48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007fffeda6cffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff7b83817 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#26 0x00007ffff7b31aaa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#27 0x00007ffff7b39a6d in QCoreApplication::exec() () from /usr/local/Qt-5.6.0/lib/libQt5Core.so.5
#28 0x0000000000546994 in main ()
```

**Comment by Emdek** [comment]
It seems that this one will require timer event fired once per second to ensure that we are filtering evens for current focus proxy widget, since I haven't found any sane way to detect change of that widget and listening for new child widgets being added is not reliable. :-/

**Comment by Emdek** [comment]
@elebow, that crash was unrelated and seems to be gone.
