### ISSUE TITLE
Started with URL opens small MDI window inside main window

### ISSUE THREAD

**Issue by cfeck** [OtterBrowser/otter-browser#1361]
To reproduce:
- run "otter-brower kde.org" from Konsole

**Comment by cfeck** [comment]
Also happens when clicking on thumbnail in the 'start page', but above can also be reproduced with a clean config.

**Comment by midluk** [comment]
If a page is opened using the address bar and then a start page thumbnail is used in a second tab, both tabs are flickering. Otter seems to cycle through both tabs in quick succession while the mouse hovers over a link in the web page or over the tab bar.

**Comment by midluk** [comment]
With the QtWebEngine backend Otter crashes as soon as the originally described problem happens. The small tab (with a new start page visible) opens, but before the actual page can be loaded the crash occurs.
<details>
<summary>Backtrace with 14779cfe50926f8c56ef927c029373c55ce6ead4 and QtWebEngine</summary>

```
#0  0x00007ffff759cf1f in QWidget::~QWidget() (this=0x15b5f60, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1602
#1  0x00007ffff759d3c9 in QWidget::~QWidget() (this=0x15b5f60, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1714
#2  0x00007fffee3a11cc in QObjectPrivate::deleteChildren() (this=this@entry=0x690ee10) at kernel/qobject.cpp:1970
#3  0x00007ffff759d0db in QWidget::~QWidget() (this=0x69128d0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1694
#4  0x00000000009ea4ea in Otter::MdiWindow::~MdiWindow() (this=0x69128d0, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/YPKJ5OE7LN/../../../src/ui/WorkspaceWidget.h:46
#5  0x00000000009ea50c in Otter::MdiWindow::~MdiWindow() (this=0x69128d0, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/YPKJ5OE7LN/../../../src/ui/WorkspaceWidget.h:46
#6  0x00007fffee39b820 in QObject::event(QEvent*) (this=this@entry=0x69128d0, e=e@entry=0x1b54140) at kernel/qobject.cpp:1254
#7  0x00007ffff75a19bb in QWidget::event(QEvent*) (this=this@entry=0x69128d0, event=event@entry=0x1b54140) at kernel/qwidget.cpp:9225
#8  0x00007ffff76c1e5b in QMdiSubWindow::event(QEvent*) (this=0x69128d0, event=0x1b54140) at widgets/qmdisubwindow.cpp:2921
#9  0x00007ffff7559ecc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x69128d0, e=0x1b54140) at kernel/qapplication.cpp:3799
#10 0x00007ffff7561671 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffd2d0, receiver=0x69128d0, e=0x1b54140) at kernel/qapplication.cpp:3556
#11 0x00007fffee3736fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x69128d0, event=event@entry=0x1b54140) at kernel/qcoreapplication.cpp:988
#12 0x00007fffee375de0 in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x1b54140, receiver=<optimized out>) at kernel/qcoreapplication.h:231
#13 0x00007fffee375de0 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=52, data=0xe6f830) at kernel/qcoreapplication.cpp:1649
#14 0x00007fffee3762b8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=52) at kernel/qcoreapplication.cpp:1503
#15 0x00007ffff16b5864 in QQuickRenderControlPrivate::windowDestroyed() (this=this@entry=0x18b58c0) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quick/items/qquickrendercontrol.cpp:181
#16 0x00007ffff16b5ae0 in QQuickRenderControl::~QQuickRenderControl() (this=0x1883f50, __in_chrg=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quick/items/qquickrendercontrol.cpp:172
#17 0x00007fffed29a823 in QQuickWidgetRenderControl::~QQuickWidgetRenderControl() (this=0x1883f50, __in_chrg=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quickwidgets/qquickwidget.cpp:70
#18 0x00007fffed29a823 in QQuickWidgetRenderControl::~QQuickWidgetRenderControl() (this=0x1883f50, __in_chrg=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quickwidgets/qquickwidget.cpp:70
#19 0x00007fffed297993 in QQuickWidgetPrivate::~QQuickWidgetPrivate() (this=0x18b5650, __in_chrg=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quickwidgets/qquickwidget.cpp:166
#20 0x00007fffed297a89 in QQuickWidgetPrivate::~QQuickWidgetPrivate() (this=0x18b5650, __in_chrg=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.7.1/src/quickwidgets/qquickwidget.cpp:172
#21 0x00007fffee3a2317 in QScopedPointerDeleter<QObjectData>::cleanup(QObjectData*) (pointer=<optimized out>) at ../../src/corelib/tools/qscopedpointer.h:60
#22 0x00007fffee3a2317 in QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::~QScopedPointer() (this=0x18b55d8, __in_chrg=<optimized out>) at ../../src/corelib/tools/qscopedpointer.h:107
#23 0x00007fffee3a2317 in QObject::~QObject() (this=<optimized out>, __in_chrg=<optimized out>) at kernel/qobject.cpp:900
#24 0x00007ffff759d153 in QWidget::~QWidget() (this=0x18b55d0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1555
#25 0x00007ffff7fa67da in QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget::~RenderWidgetHostViewQtDelegateWidget() (this=0x18b55d0, __in_chrg=<optimized out>) at ../../../src/webenginewidgets/render_widget_host_view_qt_delegate_widget.h:51
#26 0x00007ffff7fa67da in QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget::~RenderWidgetHostViewQtDelegateWidget() (this=0x18b55d0, __in_chrg=<optimized out>) at ../../../src/webenginewidgets/render_widget_host_view_qt_delegate_widget.h:51
#27 0x00007ffff1f159eb in std::default_delete<QtWebEngineCore::RenderWidgetHostViewQtDelegate>::operator()(QtWebEngineCore::RenderWidgetHostViewQtDelegate*) const (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:76
#28 0x00007ffff1f159eb in std::unique_ptr<QtWebEngineCore::RenderWidgetHostViewQtDelegate, std::default_delete<QtWebEngineCore::RenderWidgetHostViewQtDelegate> >::~unique_ptr() (this=0x18b42e0, __in_chrg=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:239
#29 0x00007ffff1f159eb in QtWebEngineCore::RenderWidgetHostViewQt::~RenderWidgetHostViewQt() (this=0x18b3ed0, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/core/render_widget_host_view_qt.cpp:255
#30 0x00007ffff1f15b79 in QtWebEngineCore::RenderWidgetHostViewQt::~RenderWidgetHostViewQt() (this=0x18b3ed0, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/core/render_widget_host_view_qt.cpp:261
#31 0x00007ffff3673f4f in content::RenderWidgetHostImpl::Destroy(bool) (this=0x1880a20, also_delete=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/renderer_host/render_widget_host_impl.cc:1435
#32 0x00007ffff3674492 in content::RenderWidgetHostImpl::ShutdownAndDestroyWidget(bool) (this=<optimized out>, also_delete=also_delete@entry=false) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/renderer_host/render_widget_host_impl.cc:432
#33 0x00007ffff36674bf in content::RenderViewHostImpl::ShutdownAndDestroy() (this=0x18a7480) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/renderer_host/render_view_host_impl.cc:885
#34 0x00007ffff37f0bce in content::FrameTree::ReleaseRenderViewHostRef(content::RenderViewHostImpl*) (this=<optimized out>, render_view_host=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/frame_tree.cc:353
#35 0x00007ffff35ddb4d in content::RenderFrameHostImpl::~RenderFrameHostImpl() (this=0x1882d50, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_impl.cc:338
#36 0x00007ffff35ddfb9 in content::RenderFrameHostImpl::~RenderFrameHostImpl() (this=0x1882d50, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_impl.cc:339
#37 0x00007ffff35e40bd in std::default_delete<content::RenderFrameHostImpl>::operator()(content::RenderFrameHostImpl*) const (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:76
#38 0x00007ffff35e40bd in std::unique_ptr<content::RenderFrameHostImpl, std::default_delete<content::RenderFrameHostImpl> >::~unique_ptr() (this=0x7fffffffc5b0, __in_chrg=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:239
#39 0x00007ffff35e40bd in content::RenderFrameHostManager::~RenderFrameHostManager() (this=0x189d420, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:83
#40 0x00007ffff37f31bb in content::FrameTreeNode::~FrameTreeNode() (this=0x189d410, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/frame_tree_node.cc:122
#41 0x00007ffff37eec7a in content::FrameTree::~FrameTree() (this=0x1695f20, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/frame_host/frame_tree.cc:113
#42 0x00007ffff37046ec in content::WebContentsImpl::~WebContentsImpl() (this=0x1695ce0, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/web_contents/web_contents_impl.cc:436
#43 0x00007ffff3704a59 in content::WebContentsImpl::~WebContentsImpl() (this=0x1695ce0, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/web_contents/web_contents_impl.cc:523
#44 0x00007ffff1f3254e in std::default_delete<content::WebContents>::operator()(content::WebContents*) const (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/6.3.1/bits/unique_ptr.h:76
#45 0x00007ffff1f3254e in std::unique_ptr<content::WebContents, std::default_delete<content::WebContents> >::reset(content::WebContents*) (__p=<optimized out>, this=0x1883dc8) at /usr/include/c++/6.3.1/bits/unique_ptr.h:347
#46 0x00007ffff1f3254e in QtWebEngineCore::WebContentsAdapterPrivate::~WebContentsAdapterPrivate() (this=0x1883db0, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/core/web_contents_adapter.cpp:348
#47 0x00007ffff1f327aa in QScopedPointerDeleter<QtWebEngineCore::WebContentsAdapterPrivate>::cleanup(QtWebEngineCore::WebContentsAdapterPrivate*) (pointer=0x1883db0) at /usr/include/qt5/QtCore/qscopedpointer.h:60
#48 0x00007ffff1f327aa in QScopedPointer<QtWebEngineCore::WebContentsAdapterPrivate, QScopedPointerDeleter<QtWebEngineCore::WebContentsAdapterPrivate> >::~QScopedPointer() (this=0x18a3080, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:107
#49 0x00007ffff1f327aa in QtWebEngineCore::WebContentsAdapter::~WebContentsAdapter() (this=0x18a3070, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/core/web_contents_adapter.cpp:387
#50 0x00007ffff7f98886 in QtSharedPointer::ExternalRefCountData::destroy() (this=0x18a3060) at /usr/include/qt5/QtCore/qsharedpointer_impl.h:161
#51 0x00007ffff7f98886 in QSharedPointer<QtWebEngineCore::WebContentsAdapter>::deref(QtSharedPointer::ExternalRefCountData*) (dd=0x18a3060) at /usr/include/qt5/QtCore/qsharedpointer_impl.h:500
#52 0x00007ffff7f98886 in QSharedPointer<QtWebEngineCore::WebContentsAdapter>::deref() (this=0x166dd50) at /usr/include/qt5/QtCore/qsharedpointer_impl.h:495
#53 0x00007ffff7f98886 in QSharedPointer<QtWebEngineCore::WebContentsAdapter>::~QSharedPointer() (this=0x166dd50, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qsharedpointer_impl.h:316
#54 0x00007ffff7f98886 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x166dd40, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/webenginewidgets/api/qwebenginepage.cpp:237
#55 0x00007ffff7f98899 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x166dd40, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/webenginewidgets/api/qwebenginepage.cpp:241
#56 0x00007ffff7f92fa0 in QScopedPointerDeleter<QWebEnginePagePrivate>::cleanup(QWebEnginePagePrivate*) (pointer=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:60
#57 0x00007ffff7f92fa0 in QScopedPointer<QWebEnginePagePrivate, QScopedPointerDeleter<QWebEnginePagePrivate> >::~QScopedPointer() (this=0x1659550, __in_chrg=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:107
#58 0x00007ffff7f92fa0 in QWebEnginePage::~QWebEnginePage() (this=0x1659540, __in_chrg=<optimized out>) at /usr/src/debug/qtwebengine-opensource-src-5.8.0/src/webenginewidgets/api/qwebenginepage.cpp:802
#59 0x00000000009ec296 in Otter::QtWebEnginePage::~QtWebEnginePage() (this=0x1659540, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEnginePage.h:34
#60 0x00000000009ec2b2 in Otter::QtWebEnginePage::~QtWebEnginePage() (this=0x1659540, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEnginePage.h:34
#61 0x00007fffee3a11cc in QObjectPrivate::deleteChildren() (this=this@entry=0x166d850) at kernel/qobject.cpp:1970
#62 0x00007ffff759d0db in QWidget::~QWidget() (this=0x166d620, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1694
#63 0x00000000007ca3a0 in Otter::WebWidget::~WebWidget() (this=0x166d620, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/src/ui/WebWidget.h:49
#64 0x00000000009ec0c2 in Otter::QtWebEngineWebWidget::~QtWebEngineWebWidget() (this=0x166d620, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEngineWebWidget.h:36
#65 0x00000000009ec0e6 in Otter::QtWebEngineWebWidget::~QtWebEngineWebWidget() (this=0x166d620, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEngineWebWidget.h:36
#66 0x00007fffee3a11cc in QObjectPrivate::deleteChildren() (this=this@entry=0x164eda0) at kernel/qobject.cpp:1970
#67 0x00007ffff759d0db in QWidget::~QWidget() (this=0x164ecc0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1694
#68 0x00000000008dc0a4 in Otter::ContentsWidget::~ContentsWidget() (this=0x164ecc0, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/src/modules/windows/addons/../../../ui/ContentsWidget.h:35
#69 0x00000000009eb2ba in Otter::WebContentsWidget::~WebContentsWidget() (this=0x164ecc0, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/RL6LEGLMRN/../../../src/modules/windows/web/WebContentsWidget.h:44
#70 0x00000000009eb2dc in Otter::WebContentsWidget::~WebContentsWidget() (this=0x164ecc0, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/RL6LEGLMRN/../../../src/modules/windows/web/WebContentsWidget.h:44
#71 0x00007fffee3a11cc in QObjectPrivate::deleteChildren() (this=this@entry=0x15b6020) at kernel/qobject.cpp:1970
#72 0x00007ffff759d0db in QWidget::~QWidget() (this=0x15b5f60, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1694
#73 0x00000000009ea5b6 in Otter::Window::~Window() (this=0x15b5f60, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/OBN3YE725W/../../../src/modules/widgets/configurationOption/../../../ui/Window.h:51
#74 0x00000000009ea5da in Otter::Window::~Window() (this=0x15b5f60, __in_chrg=<optimized out>) at /mnt/daten/Software/otter-browser/build/otter-browser_autogen/OBN3YE725W/../../../src/modules/widgets/configurationOption/../../../ui/Window.h:51
#75 0x00007fffee39b820 in QObject::event(QEvent*) (this=this@entry=0x15b5f60, e=e@entry=0x6d9abc0) at kernel/qobject.cpp:1254
#76 0x00007ffff75a19bb in QWidget::event(QEvent*) (this=0x15b5f60, event=0x6d9abc0) at kernel/qwidget.cpp:9225
#77 0x00007ffff7559ecc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x15b5f60, e=0x6d9abc0) at kernel/qapplication.cpp:3799
#78 0x00007ffff7561671 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffd2d0, receiver=0x15b5f60, e=0x6d9abc0) at kernel/qapplication.cpp:3556
#79 0x00007fffee3736fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x15b5f60, event=event@entry=0x6d9abc0) at kernel/qcoreapplication.cpp:988
#80 0x00007fffee375de0 in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x6d9abc0, receiver=<optimized out>) at kernel/qcoreapplication.h:231
#81 0x00007fffee375de0 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xe6f830) at kernel/qcoreapplication.cpp:1649
#82 0x00007fffee3762b8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1503
#83 0x00007fffee3c1653 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0xeb84f0) at kernel/qeventdispatcher_glib.cpp:276
#84 0x00007fffea8b6e52 in g_main_dispatch (context=0x7fffc80016f0) at gmain.c:3203
#85 0x00007fffea8b6e52 in g_main_context_dispatch (context=context@entry=0x7fffc80016f0) at gmain.c:3856
#86 0x00007fffea8b71d0 in g_main_context_iterate (context=context@entry=0x7fffc80016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3929
#87 0x00007fffea8b727c in g_main_context_iteration (context=0x7fffc80016f0, may_block=may_block@entry=1) at gmain.c:3990
#88 0x00007fffee3c16cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0xee6760, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#89 0x00007fffee37268a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffd180, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#90 0x00007fffee37a18c in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1261
#91 0x000000000065b6c9 in main(int, char**) (argc=1, argv=0x7fffffffd708) at /mnt/daten/Software/otter-browser/src/main.cpp:191
```
</details>

**Comment by Emdek** [comment]
@cfeck, could you please check if original issue is still reproducible using current master? I cannot reproduce it now.

**Comment by cfeck** [comment]
Referenced commit fixed it, merci :)
