### ISSUE TITLE
MDI: window title race and crash on closing tab

### ISSUE THREAD

**Issue by paradogz** [OtterBrowser/otter-browser#1494]
1. Open two tabs
2. Do Arrange -> Cascade
3. Note that the main window title keeps toggling between the two tabs titles for some time
4. Close one tab and the crash happens:

```
#0  0xffffffffffffffff in  ()#1  0x00007ffff6ab0e75 in  () at /usr/lib64/libQt5Widgets.so.5
#2  0x00007ffff6a93c33 in QWidget::clearFocus() () at /usr/lib64/libQt5Widgets.so.5
#3  0x00007ffff6a95398 in QWidget::~QWidget() () at /usr/lib64/libQt5Widgets.so.5
#4  0x00000000008b2f2e in Otter::TabHandleWidget::~TabHandleWidget() (this=0x12306f0, __in_chrg=<optimized out>)
    at /home/user/code/otter-browser-0.9.94/builddir/../src/ui/TabBarWidget.h:36
#5  0x00000000008b2f2e in Otter::TabHandleWidget::~TabHandleWidget() (this=0x12306f0, __in_chrg=<optimized out>)
    at /home/user/code/otter-browser-0.9.94/builddir/../src/ui/TabBarWidget.h:36
#6  0x00007fffedb011d8 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff6a995c3 in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff6a5541c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff6a5c836 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#10 0x00007fffedad7278 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#11 0x00007fffedad986b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib64/libQt5Core.so.5
#12 0x00007fffedb27853 in  () at /usr/lib64/libQt5Core.so.5
#13 0x00007fffe7610787 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#14 0x00007fffe76109b8 in  () at /usr/lib64/libglib-2.0.so.0
#15 0x00007fffe7610a5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#16 0x00007fffedb27c5f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib64/libQt5Core.so.5
#17 0x00007fffedad57ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#18 0x00007fffedadd81d in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#19 0x000000000055c635 in main(int, char**) (argc=1, argv=<optimized out>)
    at /home/user/code/otter-browser-0.9.94/src/main.cpp:217
```

Otter 0.9.94-WebKit on Linux

**Comment by midluk** [comment]
Still seeing the same toggling/flickering and crash with current master on Fedora 30 with WebKit.

This is also caused by any other arrange actions (tile, Maximize all, minimize all), but not by actions that affect only a single tab (like minimize, maximize or anything with only a single tab open).
This problem does not seem to occur after a successful single tab arrange action has been performed.

**Comment by midluk** [comment]
I can still reproduce this with current git master a6f985e on Fedora 30.
Minimizing and maximizing again the browser window (Plasma Desktop with KWin on X11) seems to fix the flickering and prevent the crash.
