### ISSUE TITLE
Any website with JavaScript causes crash

### ISSUE THREAD

**Issue by jjtmp** [OtterBrowser/otter-browser#1534]
Otter Browser works for simple websites (such as example.com).
But when opening Otter Browser and navigating to a website which uses JavaScript (e. g. javascript.com) the browser crashes with following backtrace:

```
Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
WebCore::JSDOMNamedConstructor<WebCore::JSHTMLImageElement>::construct ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/bindings/js/JSImageConstructor.cpp:50
50          Document* document = jsConstructor->document();
(gdb) bt
#0  WebCore::JSDOMNamedConstructor<WebCore::JSHTMLImageElement>::construct ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/bindings/js/JSImageConstructor.cpp:50
#1  0xae465de7 in handleHostCall () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:1131
#2  JSC::LLInt::setUpCall () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:1154
#3  0xae47149e in JSC::LLInt::genericCall ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:1238
#4  llint_slow_path_construct () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:1250
#5  0xae2a6b4f in llint_entry () from /usr/lib/libQt5WebKit.so.5
#6  0xae2a68d1 in llint_entry () from /usr/lib/libQt5WebKit.so.5
#7  0xae2a20bc in vmEntryToJavaScript () from /usr/lib/libQt5WebKit.so.5
#8  0xae2441ba in JSC::JITCode::execute () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/jit/JITCode.cpp:80
#9  0xae20f321 in JSC::Interpreter::execute ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/interpreter/Interpreter.cpp:971
#10 0xadfa1cac in JSC::evaluate () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/runtime/Completion.cpp:106
#11 0xadfa1f22 in JSC::profiledEvaluate () at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/JavaScriptCore/runtime/Completion.cpp:121
#12 0xaec00aa7 in WebCore::JSMainThreadExecState::profiledEvaluate ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/bindings/js/JSMainThreadExecState.h:80
#13 WebCore::ScriptController::evaluateInWorld(WebCore::ScriptSourceCode const&, WebCore::DOMWrapperWorld&, WebCore::ExceptionDetails*) ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/bindings/js/ScriptController.cpp:164
#14 0xaec00dd8 in WebCore::ScriptController::evaluate ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/bindings/js/ScriptController.cpp:180
#15 0xaea0e024 in WebCore::ScriptElement::executeScript ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/dom/ScriptElement.cpp:314
---Type <return> to continue, or q <return> to quit---
#16 0xaea11b16 in WebCore::ScriptElement::prepareScript ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/dom/ScriptElement.cpp:245
#17 0xaecb3da2 in WebCore::HTMLScriptRunner::runScript ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLScriptRunner.cpp:302
#18 0xaecb476a in WebCore::HTMLScriptRunner::execute ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLScriptRunner.cpp:175
#19 0xaeca6fe9 in WebCore::HTMLDocumentParser::runScriptsForPausedTreeBuilder ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLDocumentParser.cpp:195
#20 0xaeca98d1 in WebCore::HTMLDocumentParser::canTakeNextToken ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLDocumentParser.cpp:213
#21 WebCore::HTMLDocumentParser::pumpTokenizer ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLDocumentParser.cpp:252
#22 0xaecab52e in WebCore::HTMLDocumentParser::resumeParsingAfterScriptExecution ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/html/parser/HTMLDocumentParser.cpp:487
#23 0xaecaba21 in non-virtual thunk to WebCore::HTMLDocumentParser::notifyFinished(WebCore::CachedResource*) () from /usr/lib/libQt5WebKit.so.5
#24 0xaed6c520 in WebCore::CachedResource::checkNotify ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/loader/cache/CachedResource.cpp:296
#25 0xaed7c617 in WebCore::CachedScript::finishLoading ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/loader/cache/CachedScript.cpp:116
#26 0xaed4eda9 in WebCore::SubresourceLoader::didFinishLoading ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/loader/SubresourceLoader.cpp:428
#27 0xaf083493 in WebCore::QNetworkReplyHandler::finish ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:524
---Type <return> to continue, or q <return> to quit---
#28 0xaf082d75 in WebCore::QNetworkReplyHandlerCallQueue::flush ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:258
#29 0xaf084e49 in WebCore::QNetworkReplyWrapper::qt_static_metacall ()
    at /usr/src/debug/libqt5-qtwebkit-5.212~alpha2-5.3.i386/build/Source/WebCore/moc_QNetworkReplyHandler.cpp:181
#30 0xacdae890 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/sse2/libQt5Core.so.5
#31 0xacdaee6d in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/sse2/libQt5Core.so.5
#32 0xad18de52 in QNetworkReply::finished() () from /usr/lib/libQt5Network.so.5
#33 0xad0ec68d in ?? () from /usr/lib/libQt5Network.so.5
#34 0xad192f47 in ?? () from /usr/lib/libQt5Network.so.5
#35 0xacdab8a6 in QMetaCallEvent::placeMetaCall(QObject*) () from /usr/lib/sse2/libQt5Core.so.5
#36 0xacdaf0d3 in QObject::event(QEvent*) () from /usr/lib/sse2/libQt5Core.so.5
#37 0xb75e18a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#38 0xb75e9284 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#39 0xacd83f8f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/sse2/libQt5Core.so.5
#40 0xacd870fe in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/sse2/libQt5Core.so.5
#41 0xacd874e7 in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/sse2/libQt5Core.so.5
#42 0xacdd9cf3 in ?? () from /usr/lib/sse2/libQt5Core.so.5
#43 0xabef4f4d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#44 0xabef5211 in ?? () from /usr/lib/libglib-2.0.so.0
#45 0xabef52b4 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#46 0xacdd9299 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/sse2/libQt5Core.so.5
#47 0xa47f5463 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#48 0xacd82af1 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/sse2/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#49 0xacd8afd3 in QCoreApplication::exec() () from /usr/lib/sse2/libQt5Core.so.5
#50 0xad323831 in QGuiApplication::exec() () from /usr/lib/sse2/libQt5Gui.so.5
#51 0xb75e1814 in QApplication::exec() () from /usr/lib/libQt5Widgets.so.5
#52 0x005c21aa in main () at /usr/src/debug/otter-browser-0.9.99.1-1.1.i386/src/main.cpp:217
#53 0xac6b9011 in __libc_start_main () from /lib/libc.so.6
#54 0x005c3cca in _start () at ../sysdeps/i386/start.S:112
(gdb) 
```

I installed the 32bit binaries from openSUSE Tumbleweed repository. Version is "Otter 0.9.99 weekly RC 10" with Web-Backend WebKit-Backend 602.1

**Comment by jjtmp** [comment]
Update for version 1.0.03: I can open some websites with javascript (e.g. javascript.com) and even interact, but after this when closing the browser, I get a segmentation fault.

### Backtrace:

```
#0  0xae20e7fc in QUrl::~QUrl() () at /lib/libQt5Core.so.5
#1  0xae3256a9 in  () at /lib/libQt5Core.so.5
#2  0xae31cf64 in QVariant::clear() () at /lib/libQt5Core.so.5
#3  0xae31fc5b in QVariant::operator=(QVariant const&) ()
    at /lib/libQt5Core.so.5
#4  0x0083c120 in operator() (runResult=..., __closure=0x222bea8)
    at /usr/src/debug/otter-browser-1.0.03/src/modules/backends/web/qtwebengine/QtWebEnginePage.cpp:390
#5  QtWebEnginePrivate::QWebEngineCallbackPrivate<const QVariant&, Otter::QtWebEnginePage::runScriptSource(const QString&)::<lambda(const QVariant&)> >::operator()(const QVariant &) (this=0x222bea0, value=...)
    at /usr/include/qt5/QtWebEngineCore/qwebenginecallback.h:69
#6  0xb7f82dd2 in  () at /lib/libQt5WebEngineWidgets.so.5
#7  0xb7f81dbc in  () at /lib/libQt5WebEngineWidgets.so.5
#8  0xb7f81fc3 in QWebEnginePage::~QWebEnginePage() ()
    at /lib/libQt5WebEngineWidgets.so.5
#9  0x005b2321 in Otter::QtWebEnginePage::~QtWebEnginePage()
    (this=0x15dc190, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEnginePage.h:34
#10 Otter::QtWebEnginePage::~QtWebEnginePage()
    (this=0x15dc190, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/O47S2FX7W7/../../../src/modules/backends/web/qtwebengine/QtWebEnginePage.h:34
#11 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#12 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#13 0x00842e1d in Otter::WebWidget::~WebWidget()
    (this=0x1b46f10, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/core/ActionExecutor.cpp:135
#14 Otter::QtWebEngineWebWidget::~QtWebEngineWebWidget()
    (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/modules/backends/web/qtwebengine/QtWebEngineWebWidget.cpp:154
#15 0x0084322a in Otter::QtWebEngineWebWidget::~QtWebEngineWebWidget()
    (this=0x1b46f10, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/modules/backends/web/qtwebengine/QtWebEngineWebWidget.cpp:154
#16 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#17 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#18 0xb761fb7d in QFrame::~QFrame() () at /lib/libQt5Widgets.so.5
#19 0xb76f2ed5 in QSplitter::~QSplitter() () at /lib/libQt5Widgets.so.5
#20 0x006fa94a in Otter::SplitterWidget::~SplitterWidget()
    (this=0xe5d600, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/ui/SplitterWidget.h:30
#21 Otter::SplitterWidget::~SplitterWidget()
    (this=0xe5d600, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/ui/SplitterWidget.h:30
#22 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#23 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#24 0x005a9130 in Otter::ContentsWidget::~ContentsWidget()
    (this=0x1b0d130, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/NWLDKIYARD/../../../src/modules/windows/addons/../../../ui/ContentsWidget.h:33
#25 Otter::WebContentsWidget::~WebContentsWidget()
    (this=0x1b0d130, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/RL6LEGLMRN/../../../src/modules/windows/web/WebContentsWidget.h:42
#26 Otter::WebContentsWidget::~WebContentsWidget()
    (this=0x1b0d130, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/RL6LEGLMRN/../../../src/modules/windows/web/WebContentsWidget.h:42
#27 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#28 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#29 0x005a44f9 in Otter::Window::~Window()
    (this=0xe9ad70, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/OBN3YE725W/../../../src/modules/widgets/configurationOption/../../../ui/Window.h:47
#30 Otter::Window::~Window() (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/OBN3YE725W/../../../src/modules/widgets/configurationOption/../../../ui/Window.h:47
#31 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#32 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#33 0x0059fc4a in Otter::WorkspaceWidget::~WorkspaceWidget()
    (this=0xd90810, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/YPKJ5OE7LN/../../../src/ui/WorkspaceWidget.h:69
#34 Otter::WorkspaceWidget::~WorkspaceWidget()
    (this=0xd90810, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/build/otter-browser_autogen/YPKJ5OE7LN/../../../src/ui/WorkspaceWidget.h:69
#35 0xae303a89 in QObjectPrivate::deleteChildren() () at /lib/libQt5Core.so.5
#36 0xb75664e9 in QWidget::~QWidget() () at /lib/libQt5Widgets.so.5
#37 0xb76910cd in QMainWindow::~QMainWindow() () at /lib/libQt5Widgets.so.5
#38 0x006af543 in Otter::MainWindow::~MainWindow()
    (this=0xc052f0, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/core/ActionExecutor.cpp:135
#39 0x006af87a in Otter::MainWindow::~MainWindow()
    (this=0xc052f0, this=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/ui/MainWindow.cpp:235
#40 0xae305db1 in QObject::event(QEvent*) () at /lib/libQt5Core.so.5
#41 0xb756ae1f in QWidget::event(QEvent*) () at /lib/libQt5Widgets.so.5
#42 0xb769300b in QMainWindow::event(QEvent*) () at /lib/libQt5Widgets.so.5
#43 0x006c0c73 in Otter::MainWindow::event(QEvent*)
    (this=<optimized out>, event=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/ui/MainWindow.cpp:2719
#44 0xb7523da6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/libQt5Widgets.so.5
#45 0xb752b8a4 in QApplication::notify(QObject*, QEvent*) ()
    at /lib/libQt5Widgets.so.5
#46 0xae2d6fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/libQt5Core.so.5
#47 0xae2d7238 in QCoreApplication::sendEvent(QObject*, QEvent*) ()
    at /lib/libQt5Core.so.5
#48 0xae2daa04 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/libQt5Core.so.5
#49 0xae2daf27 in QCoreApplication::sendPostedEvents(QObject*, int) ()
    at /lib/libQt5Core.so.5
#50 0xae3369e3 in  () at /lib/libQt5Core.so.5
#51 0xad6f10ac in  () at /lib/libglib-2.0.so.0
#52 0xad6f2de7 in  () at /lib/libglib-2.0.so.0
#53 0xad6f3554 in g_main_context_iteration () at /lib/libglib-2.0.so.0
#54 0xae336085 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQt5Core.so.5
#55 0xa2abe781 in  () at /lib/libQt5XcbQpa.so.5
#56 0xae2d70d0 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQt5Core.so.5
#57 0x00724a49 in Otter::TrayIcon::hide() (this=0xda2a60)
    at /usr/include/qt5/QtCore/qflags.h:121
#58 0xae312863 in  () at /lib/libQt5Core.so.5
#59 0xae2d5e91 in QCoreApplication::aboutToQuit(QCoreApplication::QPrivateSignal) () at /lib/libQt5Core.so.5
#60 0xae2daf7d in QCoreApplicationPrivate::execCleanup() ()
    at /lib/libQt5Core.so.5
#61 0xae2de6fc in QCoreApplication::exec() () at /lib/libQt5Core.so.5
#62 0xae934d81 in QGuiApplication::exec() () at /lib/libQt5Gui.so.5
#63 0xb7523d14 in QApplication::exec() () at /lib/libQt5Widgets.so.5
#64 0x005767e8 in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/otter-browser-1.0.03/src/main.cpp:217
```
