### ISSUE TITLE
Otter-browser segfault for build on MINGW64 

### ISSUE THREAD

**Issue by spl1inter** [OtterBrowser/otter-browser#1537]
QT Information:
I:\MSYS2\mingw64\bin>qmake --version
QMake version 3.1
Using Qt version 5.11.1 in I:/MSYS2/mingw64/lib

gdb backtrace:
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006ddd40c0 in QFontDatabase::removeApplicationFont(int) ()
   from I:\MSYS2\mingw64\bin\Qt5Guid.dll
(gdb) bt full
#0  0x000000006ddd40c0 in QFontDatabase::removeApplicationFont(int) ()
   from I:\MSYS2\mingw64\bin\Qt5Guid.dll
No symbol table info available.
#1  0x000000006ddd631b in QFontDatabase::addApplicationFontFromData(QByteArray c
onst&) () from I:\MSYS2\mingw64\bin\Qt5Guid.dll
No symbol table info available.
#2  0x000000006ddd6579 in QFontDatabase::addApplicationFontFromData(QByteArray c
onst&) () from I:\MSYS2\mingw64\bin\Qt5Guid.dll
No symbol table info available.
#3  0x000000006ddb9fd9 in QFont::defaultFamily() const ()
   from I:\MSYS2\mingw64\bin\Qt5Guid.dll
No symbol table info available.
#4  0x000000000324a703 in QWebSettings::QWebSettings() ()
   from I:\MSYS2\mingw64\bin\Qt5WebKitd.dll
No symbol table info available.
#5  0x000000000324c848 in QWebSettings::globalSettings() ()
   from I:\MSYS2\mingw64\bin\Qt5WebKitd.dll
No symbol table info available.
#6  0x000000000324cb56 in QWebSettings::setOfflineStoragePath(QString const&)
    () from I:\MSYS2\mingw64\bin\Qt5WebKitd.dll
No symbol table info available.
#7  0x0000000000652892 in Otter::QtWebKitWebBackend::QtWebKitWebBackend(QObject*
) ()
No symbol table info available.
#8  0x000000000041964c in Otter::AddonsManager::AddonsManager(QObject*) ()
No symbol table info available.
#9  0x000000000041bca8 in Otter::AddonsManager::createInstance() ()
No symbol table info available.
#10 0x00000000004236ac in Otter::Application::Application(int&, char**) ()
No symbol table info available.
#11 0x0000000000401e3e in main ()

**Comment by spl1inter** [comment]
Issue identified as incompatible QT version resulting in unpredictable program behaviour.

Compiling earlier versions of Otter Browser (Beta 10) against MinGW64 stock library runs normally.

This issue can be closed.
