### ISSUE TITLE
Otter QWebInspector Crash under MinGW64, QT 5.12.1

### ISSUE THREAD

**Issue by spl1inter** [OtterBrowser/otter-browser#1592]
Can a QTWebkit specialist suggest what causes this QWebInspector crash in Otter when [building under MinGW64](https://github.com/msys2/MINGW-packages/issues/5734)?

```
#0  0x0000000001a5ac4c in WTFCrash () from D:\MSYS2\mingw64\bin\Qt5WebKit.dll
No symbol table info available.
#1  0x0000000002c44143 in Inspector::InjectedScriptManager::injectedScriptFor(JS
C::ExecState*) () from D:\MSYS2\mingw64\bin\Qt5WebKit.dll
No symbol table info available.
#2  0x0000000001c6208d in WebCore::InspectorFrontendClientLocal::openInNewTab(WT
F::String const&) () from D:\MSYS2\mingw64\bin\Qt5WebKit.dll
No symbol table info available.
#3  0x0000000001c98fb9 in WebCore::InspectorController::getHighlight(WebCore::Hi
ghlight&, WebCore::InspectorOverlay::CoordinateSystem) const ()
   from D:\MSYS2\mingw64\bin\Qt5WebKit.dll
No symbol table info available.
#4  0x00000000017e4184 in QWebPageAdapter::triggerAction(QWebPageAdapter::MenuAc
tion, QWebHitTestResultPrivate*, char const*, bool) ()
   from D:\MSYS2\mingw64\bin\Qt5WebKit.dll
No symbol table info available.
#5  0x00000000659501e0 in QWebPage::triggerAction(QWebPage::WebAction, bool)
    () from D:\MSYS2\mingw64\bin\Qt5WebKitWidgets.dll
```

QT 5.12.1, QTWebkit, 5.212.0-alpha2
Thanks.

**Comment by Frenzie** [comment]
Web Template Framework Crash? Sounds evocative. :-P

**Comment by spl1inter** [comment]
For now I have applied a [generic fix](https://github.com/msys2/MINGW-packages/issues/5733#issuecomment-522919388), it doesn't address all issues but prevents the crash and we still have a somewhat usable webinspector. I still think this should be reported to upstream since many voted in the past to keep the MinGW support.
