### ISSUE TITLE
crash when inspecting an image in the html debugger

### ISSUE THREAD

**Issue by timemaster67** [OtterBrowser/otter-browser#919]
1. go to google.com
2. right click the image in the middle. Click Inspect element
3. the <img alt   tag will be selected. Double click on the jpg file inside the src="" attribute
4. you get the ressource page. the image will be shown in the right and at your left you get a list of ressources. Double click on the selected (currently shown) image. the browser crash with the following error trapped in the console : 

Debug: QNetworkReplyImpl::_q_startOperation was called more than once ((null):0, (null))
Erreur de segmentation (core dumped)

**Comment by The-Compiler** [comment]
I can reproduce this with otter, but not with `test-qtwebkit`. I tried with the Chromium logo, as the Google logo is a `div` element.

Stacktrace:

```
#0  0x00007ffff423dc3a in QWebPageAdapter::handleSoftwareInputPanel(Qt::MouseButton, QPoint const&) ()
   from /usr/lib/libQt5WebKit.so.5
#1  0x00007ffff423de9f in QWebPageAdapter::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5WebKit.so.5
#2  0x00007ffff6d0f041 in QWebPage::event(QEvent*) () from /usr/lib/libQt5WebKitWidgets.so.5
#3  0x00007ffff6d10000 in QWebView::mouseDoubleClickEvent(QMouseEvent*) ()
   from /usr/lib/libQt5WebKitWidgets.so.5
#4  0x00007ffff65ecf08 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff6d114ab in QWebView::event(QEvent*) () from /usr/lib/libQt5WebKitWidgets.so.5
#6  0x00007ffff65aa00c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff65afbe9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff2e7889b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff65aeaf2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff660774b in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff6609cfb in ?? () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff65aa00c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff65af4e6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff2e7889b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff33d7c81 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)
    () from /usr/lib/libQt5Gui.so.5
#16 0x00007ffff33d9955 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#17 0x00007ffff33bee08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () from /usr/lib/libQt5Gui.so.5
#18 0x00007fffe3ab09f0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#19 0x00007ffff0f3e9fd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#20 0x00007ffff0f3ece0 in ?? () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff0f3ed8c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#22 0x00007ffff2ecf23f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#23 0x00007ffff2e7626a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#24 0x00007ffff2e7e20c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#25 0x0000555555621338 in main ()
```

**Comment by Emdek** [comment]
It seems to work fine with revived QtWebKit, legacy SDK versions crash.

**Comment by annulen** [comment]
I don't think it's fixed, just hidden by something else. BTW, Google does not use <img> for logo anymore, they use background of <div> now

**Comment by Emdek** [comment]
@annulen, well, at least it is no longer reproducible. ;-)
