### ISSUE TITLE
Segfault after closing

### ISSUE THREAD

**Issue by EXL** [OtterBrowser/otter-browser#956]
```
(gdb) bt full
#0  0x00007ffff3227128 in QIcon::~QIcon() () from /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5
No symbol table info available.
#1  0x00007ffff32349c7 in ?? () from /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5
No symbol table info available.
#2  0x00007ffff322eb4f in ?? () from /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5
No symbol table info available.
#3  0x00007ffff322712b in QIcon::~QIcon() () from /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5
No symbol table info available.
#4  0x00000000005251b5 in Otter::ActionDefinition::~ActionDefinition (this=0xc8fb30, __in_chrg=<optimized out>) at /storage/exl/Projects/Otter-Browser/src/core/ActionsManager.h:30
No locals.
#5  0x0000000000527a46 in QVector<Otter::ActionDefinition>::destruct (this=0xabb030 <Otter::ActionsManager::m_definitions>, from=0xc8fb58, to=0xc90b20)
    at /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h:313
No locals.
#6  0x00000000005275d7 in QVector<Otter::ActionDefinition>::freeData (this=0xabb030 <Otter::ActionsManager::m_definitions>, x=0xc8f140)
    at /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h:483
No locals.
#7  0x0000000000525eb6 in QVector<Otter::ActionDefinition>::~QVector (this=0xabb030 <Otter::ActionsManager::m_definitions>, __in_chrg=<optimized out>)
    at /opt/QtSDKs/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h:68
No locals.
#8  0x00007ffff1a5ed32 in __run_exit_handlers (status=0, listp=0x7ffff1de9698 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
#9  0x00007ffff1a5ed85 in __GI_exit (status=<optimized out>) at exit.c:104
No locals.
#10 0x00007ffff1a45a47 in __libc_start_main (main=0x516213 <main(int, char**)>, argc=1, argv=0x7fffffffdd48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd38) at libc-start.c:323
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 7096899206532707871, 5331568, 140737488346432, 0, 0, -7096899862435580385, -7096930180457679329}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x744ce0 <__libc_csu_init>, 0x7fffffffdd48}, data = {prev = 0x0, cleanup = 0x0, canceltype = 7621856}}}
        not_first_call = <optimized out>
#11 0x0000000000515a99 in _start ()
No symbol table info available.
```

Qt 5.4.1
Otter 0.9.08-dev, building from commit 717671bb16b121a6f99c4ad201fdf0ac911c0ae4
Web backend: WebKit Backend 538.1.
SSL library version: OpenSSL 1.0.1f 6 Jan 2014.

**Comment by Chocimier** [comment]
Thank you for report, but we already have one about this: #889
